/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.cput.Users;

import javax.swing.JOptionPane;

/**
 *
 * @author Mbuso Kotob's
 */
public class UpdateUserView extends javax.swing.JFrame {
    
    private int ID;
    UserDBOperations dbOperation = new UserDBOperations();
    
    /**
     * Creates new form UpdateUser
     */
    public UpdateUserView()
    {
        initComponents();
    }
    
    public UpdateUserView(int id)
    {
        this.ID = id;
        initComponents();
        addDataToUpdateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        userIdLabel = new javax.swing.JLabel();
        userIDField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cellphoneField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox<>();
        updateUserDetailsBtn = new javax.swing.JToggleButton();
        detailEditCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(178, 149, 213));

        userIdLabel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        userIdLabel.setText("User Id");

        userIDField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));
        userIDField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userIDFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        firstNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        lastNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        cellphoneField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Cellphone");

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("User Type");

        userTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee" }));
        userTypeComboBox.setSelectedIndex(1);
        userTypeComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 2, true));

        updateUserDetailsBtn.setBackground(new java.awt.Color(178, 149, 213));
        updateUserDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateUserDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateUserDetailsBtn.setText("Update User Details");
        updateUserDetailsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 1, true));
        updateUserDetailsBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateUserDetailsBtnActionPerformed(evt);
            }
        });

        detailEditCancelBtn.setBackground(new java.awt.Color(178, 149, 213));
        detailEditCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        detailEditCancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailEditCancelBtn.setText("Cancel");
        detailEditCancelBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 173, 104), 1, true));
        detailEditCancelBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                detailEditCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailEditCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDField)
                    .addComponent(firstNameField)
                    .addComponent(lastNameField)
                    .addComponent(emailField)
                    .addComponent(cellphoneField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField)
                    .addComponent(updateUserDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIdLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailEditCancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(updateUserDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIDFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userIDFieldActionPerformed
    {//GEN-HEADEREND:event_userIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDFieldActionPerformed

    private void updateUserDetailsBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateUserDetailsBtnActionPerformed
    {//GEN-HEADEREND:event_updateUserDetailsBtnActionPerformed
        extractValuesFromFormFields();
        this.dbOperation.updateUser(new User(this.id, this.firstName, this.lastName, this.email, this.cellphone, this.userType, this.password));
        JOptionPane.showMessageDialog(null, "Details Successfully Updated");
        this.dispose();
        UsersView userView = new UsersView();
        userView.setVisible(true);
    }//GEN-LAST:event_updateUserDetailsBtnActionPerformed

    private void detailEditCancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_detailEditCancelBtnActionPerformed
    {//GEN-HEADEREND:event_detailEditCancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_detailEditCancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UpdateUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UpdateUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UpdateUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UpdateUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new UpdateUserView().setVisible(true);
            }
        });
    }
    
    private void addDataToUpdateForm()
    {
        User user = dbOperation.getUser(this.ID);
        userIDField.setText(String.valueOf(user.getId()));
        firstNameField.setText(user.getFirstName());
        lastNameField.setText(user.getLastName());
        emailField.setText(user.getEmail());
        cellphoneField.setText(user.getCellphone());
        if(user.getUserType().equalsIgnoreCase("Admin"))
        {
            userTypeComboBox.setSelectedIndex(0);
        } 
        else {
            userTypeComboBox.setSelectedIndex(1);
        }
        passwordField.setText(user.getPassword());
    }
    
    private void extractValuesFromFormFields()
    {
        this.id = Integer.parseInt(this.userIDField.getText());
        this.firstName = this.firstNameField.getText();
        this.lastName = this.lastNameField.getText();
        this.email = this.emailField.getText();
        this.cellphone = this.cellphoneField.getText();
        this.userType = this.userTypeComboBox.getSelectedItem().toString();
        this.password = this.passwordField.getText();
    }
    
    private int id = 0;
    private String firstName = "";
    private String lastName = "";
    private String email = "";
    private String cellphone = "";
    private String userType = "";
    private String password = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cellphoneField;
    private javax.swing.JButton detailEditCancelBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JToggleButton updateUserDetailsBtn;
    private javax.swing.JTextField userIDField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JComboBox<String> userTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
